language: python
python:
  - "3.5"
  - "3.6"
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
install: pip install .[test] codecov
script: pytest -m "not selenium"
after_success: codecov
